# from what image we want to build from
FROM node:8

# Create app directory
WORKDIR /d/Web-Tutorials/Node-Graphql-Server/SpaceX-GraphQL-Server

# Ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Building for development
RUN npm install

# Building for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# expose port to be mapped by the docker daemon
EXPOSE 8080

# Command to run server
CMD [ "npm", "start" ]
